---
deployment:
  tasks:
    - /opt/cpanel/ea-nodejs18/bin/npm install  # Instalar dependencias
    - /opt/cpanel/ea-nodejs18/bin/npm run build  # Construir la aplicación
    - rsync -a build/ ~/public_html/  # Mover la app construida a public_html
